#!/usr/bin/env bash

# https://stackoverflow.com/a/246128/715866
SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"

source "$(dirname "$SCRIPT_DIR")/utils/handle-startup"
source "$(dirname "$SCRIPT_DIR")/utils/get-client"

CLIENT=$(get-client)

if [[ "$CLIENT" == yadm ]]; then
  LS_FILES_OPTIONS=" --modified --exclude-standard"
else
  LS_FILES_OPTIONS=" --modified --others --exclude-standard"
fi

REPO_ROOT=$(git rev-parse --show-toplevel)
if FILES=$("$CLIENT" ls-files "$LS_FILES_OPTIONS" "$REPO_ROOT"); then
  # This error message is based on the error message that is printed if "git
  # log" is run in an empty repository
  if [[ -z "$FILES" ]]; then
    >&2 echo "fatal: you do not have any files to add"
    exit 4
  fi

  if SELECTED_FILES=$(fzf --multi <<< "$FILES"); then
    xargs --no-run-if-empty "$CLIENT" add <<< "$SELECTED_FILES"
  fi
fi
