#!/usr/bin/env bash

# Handle startup
# https://stackoverflow.com/a/246128/715866
SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
source "$(dirname "$SCRIPT_DIR")/utils/handle-startup"

if [[ "$*" == "--remotes" ]]; then
  GIT_BRANCH_OPTIONS="--remotes"
fi

if BRANCHES=$(git branch --format='%(refname:short)' $GIT_BRANCH_OPTIONS); then
  # This error message is based on the error message that is printed if "git
  # log" is run in an empty repository
  if [[ -z "$BRANCHES" ]]; then
    >&2 echo "fatal: your repository does not have any branches with commits yet"
    exit 4
  fi

  if SELECTED_BRANCH=$(fzf <<< "$BRANCHES"); then
    git switch "$SELECTED_BRANCH"
  fi
fi
