#!/usr/bin/env bash

# Handle startup
# https://stackoverflow.com/a/246128/715866
SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
source "$(dirname "$SCRIPT_DIR")/utils/handle-startup"

function get-files() {
  REPO_ROOT=$(git rev-parse --show-toplevel)
  (
    git diff --name-only --relative --staged
    git ls-files --modified --others --exclude-standard "$REPO_ROOT"
  ) | sort --unique
}

if FILES=$(get-files); then
  # This error message is based on the error message that is printed if "git
  # log" is run in an empty repository
  if [[ -z "$FILES" ]]; then
    >&2 echo "fatal: you do not have any staged files which can be committed"
    exit 4
  fi

  if SELECTED_FILES=$(fzf --multi <<< "$FILES"); then
    xargs --no-run-if-empty git commit <<< "$SELECTED_FILES"
  fi
fi
