#!/usr/bin/env bash

# Source utils
# https://stackoverflow.com/a/246128/715866
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "$(dirname "$SCRIPT_DIR")/utils"

handle-startup

if FILES=$(git diff --name-only --relative); then
  if [[ -z "$FILES" ]]; then
    print-fatal-error "you do not have any files to restore"
    exit 4
  fi

  if SELECTED_FILES=$(fzf --multi <<< "$FILES"); then
    xargs --no-run-if-empty git restore <<< "$SELECTED_FILES"
  fi
fi
