#!/usr/bin/env bash

# Source utils
# https://stackoverflow.com/a/246128/715866
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "$(dirname "$SCRIPT_DIR")/utils"

handle-startup

function get-files() {
  REPO_ROOT=$(git rev-parse --show-toplevel)
  (
    git diff --name-only --relative --staged
    git ls-files --modified --others --exclude-standard "$REPO_ROOT"
  ) | sort --unique
}

if FILES=$(get-files); then
  if [[ -z "$FILES" ]]; then
    print-fatal-error "you do not have any staged files which can be committed"
    exit 4
  fi

  if SELECTED_FILES=$(fzf --multi <<< "$FILES"); then
    xargs --no-run-if-empty git commit <<< "$SELECTED_FILES"
  fi
fi
