#!/usr/bin/env bash

# Source utils
# https://stackoverflow.com/a/246128/715866
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "$(dirname "$SCRIPT_DIR")/utils"

handle-startup

if [[ "$*" == "--staged" ]]; then
  GIT_DIFF_OPTIONS="--staged"
fi

if FILES=$(git diff --name-only --relative $GIT_DIFF_OPTIONS); then
  if [[ -z "$FILES" ]]; then
    handle-fatal-error "you do not have any files to diff"
  fi

  if SELECTED_FILES=$(fzf --multi <<< "$FILES"); then
    xargs --no-run-if-empty git difftool --no-prompt $GIT_DIFF_OPTIONS <<< "$SELECTED_FILES"
  fi
fi
