#!/usr/bin/env bash

# Source utils
# https://stackoverflow.com/a/246128/715866
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "$(dirname "$SCRIPT_DIR")/utils"

handle-startup

CLIENT=$(get-client)
LS_FILES_OPTIONS=$(get-ls-files-options "$CLIENT")

REPO_ROOT=$(eval "$CLIENT rev-parse --show-toplevel")
if FILES=$(eval "$CLIENT ls-files $LS_FILES_OPTIONS $REPO_ROOT"); then
  if [[ -z "$FILES" ]]; then
    exit-with-applicability-error "you do not have any files to add"
  fi

  if SELECTED_FILES=$(fzf --multi <<< "$FILES"); then
    eval "xargs --no-run-if-empty $CLIENT add <<< $SELECTED_FILES"
  fi
fi
