#!/usr/bin/env bash

# Source utils
# https://stackoverflow.com/a/246128/715866
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "$(dirname "$SCRIPT_DIR")/utils"

handle-startup

REMOTES=false

if [[ "$*" == "--remotes" ]]; then
  REMOTES=true
  GIT_BRANCH_OPTIONS="--remotes"
fi

if BRANCHES=$(git branch --format='%(refname:short)' $GIT_BRANCH_OPTIONS); then
  if [[ -z "$BRANCHES" ]]; then
    handle-fatal-error "your repository does not have any branches with commits yet"
  fi

  if SELECTED_BRANCH=$(fzf <<< "$BRANCHES"); then
    if [[ $REMOTES == true ]]; then
      git switch --track "$SELECTED_BRANCH"
    else
      git switch "$SELECTED_BRANCH"
    fi

  fi
fi
